### ISSUE TITLE
Lost device after running for a while

### ISSUE THREAD

**Issue by s1oz** [dmacias72/NUT-unRAID#18]
Lost UPS after running for a while, NUT plugin shows running, but no UPS device shows
After re-plugging and unplugging the USB, restart the NUT plugin and enable it normally
```
Scanning for UPS...

[nutdev1]
driver = "usbhid-ups"
port = "auto"
vendorid = "051D"
productid = "0002"
product = "BK650M2-CH"
serial = "9B2019A13037"
vendor = "American Power Conversion"
bus = "001"
```

> Feb  1 11:03:10 Tower upsmon[14759]: Poll UPS [ups@127.0.0.1] failed - Data stale
Feb  1 11:03:11 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:13 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:15 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:15 Tower upsmon[14759]: Poll UPS [ups@127.0.0.1] failed - Data stale
Feb  1 11:03:17 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:19 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:20 Tower upsmon[14759]: Poll UPS [ups@127.0.0.1] failed - Data stale
Feb  1 11:03:21 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:23 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:25 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:25 Tower upsmon[14759]: Poll UPS [ups@127.0.0.1] failed - Data stale
Feb  1 11:03:27 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:29 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:30 Tower upsmon[14759]: Poll UPS [ups@127.0.0.1] failed - Data stale
Feb  1 11:03:31 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:33 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:35 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:35 Tower upsmon[14759]: Poll UPS [ups@127.0.0.1] failed - Data stale
Feb  1 11:03:37 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:39 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:40 Tower upsmon[14759]: Poll UPS [ups@127.0.0.1] failed - Data stale
Feb  1 11:03:41 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:43 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:45 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:45 Tower upsmon[14759]: Poll UPS [ups@127.0.0.1] failed - Data stale
Feb  1 11:03:47 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:49 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:50 Tower upsmon[14759]: Poll UPS [ups@127.0.0.1] failed - Data stale
Feb  1 11:03:51 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:53 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:55 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround
Feb  1 11:03:55 Tower upsmon[14759]: Poll UPS [ups@127.0.0.1] failed - Data stale
Feb  1 11:03:57 Tower usbhid-ups[13944]: device->Product is NULL so it is not possible to determine whether to activate max_report_size workaround

**Comment by ds-sebastian** [comment]
@s1oz Do you recall how or if you were able to address this? I'm having this same issue and have tried different USB ports and cables with no luck.

**Comment by s1oz** [comment]
> @s1oz Do you recall how or if you were able to address this? I'm having this same issue and have tried different USB ports and cables with no luck.

I connected the Synology NAS directly via usb. Use [slave] on unraid
